INFO: Scrapy 2.6.1 started (bot: webber)
INFO: Versions: lxml 4.8.0.0, libxml2 2.9.12, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 22.2.0, Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)], pyOpenSSL 22.0.0 (OpenSSL 1.1.1n  15 Mar 2022), cryptography 36.0.2, Platform Windows-10-10.0.19044-SP0
INFO: Overridden settings:
{'BOT_NAME': 'webber',
 'LOG_FILE': 'log.txt',
 'LOG_FORMAT': '%(levelname)s: %(message)s',
 'NEWSPIDER_MODULE': 'webscraper.webscraper_package.spiders',
 'SPIDER_MODULES': ['webscraper.webscraper_package.spiders'],
 'USER_AGENT': ('Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) '
                'Gecko/20100101 Firefox/88.0',)}
DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
INFO: Telnet Password: 9fb062f4f04fc8e6
INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
INFO: Enabled item pipelines:
['webscraper.webscraper_package.pipelines.WebberPipeline']
INFO: Spider opened
INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
INFO: Telnet console listening on 127.0.0.1:6023
DEBUG: Attempting to acquire lock 2921930499328 on C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\tldextract\.suffix_cache/publicsuffix.org-tlds\de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
DEBUG: Lock 2921930499328 acquired on C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\tldextract\.suffix_cache/publicsuffix.org-tlds\de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
DEBUG: Attempting to acquire lock 2921930500672 on C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\tldextract\.suffix_cache/urls\62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
DEBUG: Lock 2921930500672 acquired on C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\tldextract\.suffix_cache/urls\62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
DEBUG: Attempting to release lock 2921930500672 on C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\tldextract\.suffix_cache/urls\62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
DEBUG: Lock 2921930500672 released on C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\tldextract\.suffix_cache/urls\62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
DEBUG: Attempting to release lock 2921930499328 on C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\tldextract\.suffix_cache/publicsuffix.org-tlds\de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
DEBUG: Lock 2921930499328 released on C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\tldextract\.suffix_cache/publicsuffix.org-tlds\de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
DEBUG: Crawled (200) <GET https://www.foodie.fi/stores/?query=Prisma%20Olari> (referer: None)
DEBUG: Crawled (200) <GET https://www.foodie.fi/stores/?query=Prisma%20Sello> (referer: None)
DEBUG: Crawled (200) <GET https://www.foodie.fi/stores/?query=S-market%20Grani> (referer: None)
DEBUG: Redirecting (302) to <GET https://www.foodie.fi/store/0563cf74f373b2250360e756060fdb59> from <GET https://www.foodie.fi/store/select_store/0563cf74f373b2250360e756060fdb59>
DEBUG: Redirecting (302) to <GET https://www.foodie.fi/store/4644aceccccd7ab8787cdfa92eb0020f> from <GET https://www.foodie.fi/store/select_store/4644aceccccd7ab8787cdfa92eb0020f>
DEBUG: Redirecting (302) to <GET https://www.foodie.fi/store/6c6a1d4de1a6454f30a3a5c185e51c08> from <GET https://www.foodie.fi/store/select_store/6c6a1d4de1a6454f30a3a5c185e51c08>
DEBUG: Crawled (200) <GET https://www.foodie.fi/store/0563cf74f373b2250360e756060fdb59> (referer: https://www.foodie.fi/stores/?query=Prisma%20Olari)
DEBUG: Crawled (200) <GET https://www.foodie.fi/store/6c6a1d4de1a6454f30a3a5c185e51c08> (referer: https://www.foodie.fi/stores/?query=S-market%20Grani)
DEBUG: Crawled (200) <GET https://www.foodie.fi/store/4644aceccccd7ab8787cdfa92eb0020f> (referer: https://www.foodie.fi/stores/?query=Prisma%20Sello)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Sandels> (referer: https://www.foodie.fi/store/0563cf74f373b2250360e756060fdb59)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Riisi> (referer: https://www.foodie.fi/store/0563cf74f373b2250360e756060fdb59)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Sandels> (referer: https://www.foodie.fi/store/0563cf74f373b2250360e756060fdb59)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\engine\base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: store_products.store_id, store_products.product_ean

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 74, in add_product
    store.products.append(store_product)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\attributes.py", line 481, in __get__
    return self.impl.get(state, dict_)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\attributes.py", line 941, in get
    value = self._fire_loader_callables(state, key, passive)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\attributes.py", line 977, in _fire_loader_callables
    return self.callable_(state, passive)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\strategies.py", line 911, in _load_for_state
    return self._emit_lazyload(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\strategies.py", line 1047, in _emit_lazyload
    result = session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1640, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\context.py", line 319, in orm_pre_session_exec
    session._autoflush()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 2237, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 2226, in _autoflush
    self.flush()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 3363, in flush
    self._flush(objects)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 3502, in _flush
    with util.safe_reraise():
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 3463, in _flush
    flush_context.execute()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\engine\base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\sql\elements.py", line 326, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\engine\base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\engine\base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\engine\base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\engine\base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Riisi> (referer: https://www.foodie.fi/store/0563cf74f373b2250360e756060fdb59)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Pasta> (referer: https://www.foodie.fi/store/0563cf74f373b2250360e756060fdb59)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Sandels> (referer: https://www.foodie.fi/store/6c6a1d4de1a6454f30a3a5c185e51c08)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Pasta> (referer: https://www.foodie.fi/store/0563cf74f373b2250360e756060fdb59)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Pasta> (referer: https://www.foodie.fi/store/6c6a1d4de1a6454f30a3a5c185e51c08)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Kana> (referer: https://www.foodie.fi/store/0563cf74f373b2250360e756060fdb59)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Sandels> (referer: https://www.foodie.fi/store/6c6a1d4de1a6454f30a3a5c185e51c08)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Kana> (referer: https://www.foodie.fi/store/6c6a1d4de1a6454f30a3a5c185e51c08)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Pasta> (referer: https://www.foodie.fi/store/6c6a1d4de1a6454f30a3a5c185e51c08)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Riisi> (referer: https://www.foodie.fi/store/6c6a1d4de1a6454f30a3a5c185e51c08)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Kana> (referer: https://www.foodie.fi/store/0563cf74f373b2250360e756060fdb59)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Kana> (referer: https://www.foodie.fi/store/6c6a1d4de1a6454f30a3a5c185e51c08)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Sandels> (referer: https://www.foodie.fi/store/4644aceccccd7ab8787cdfa92eb0020f)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Riisi> (referer: https://www.foodie.fi/store/6c6a1d4de1a6454f30a3a5c185e51c08)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Kana> (referer: https://www.foodie.fi/store/4644aceccccd7ab8787cdfa92eb0020f)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Sandels> (referer: https://www.foodie.fi/store/4644aceccccd7ab8787cdfa92eb0020f)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Riisi> (referer: https://www.foodie.fi/store/4644aceccccd7ab8787cdfa92eb0020f)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Kana> (referer: https://www.foodie.fi/store/4644aceccccd7ab8787cdfa92eb0020f)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Riisi> (referer: https://www.foodie.fi/store/4644aceccccd7ab8787cdfa92eb0020f)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
DEBUG: Crawled (200) <GET https://www.foodie.fi/products/search2?term=Pasta> (referer: https://www.foodie.fi/store/4644aceccccd7ab8787cdfa92eb0020f)
ERROR: Spider error processing <GET https://www.foodie.fi/products/search2?term=Pasta> (referer: https://www.foodie.fi/store/4644aceccccd7ab8787cdfa92eb0020f)
Traceback (most recent call last):
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 57, in wrapper
    return callback(response, **kwargs)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 188, in process_product_search
    self.export_data(command=DBAddProduct, data=page.products, store_name=store_name)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber.py", line 199, in export_data
    self.database_query(command=command, **payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\webscraper_package\spiders\webber_package\spider.py", line 28, in database_query
    result = func.execute()
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\commands.py", line 52, in execute
    self.receiver.add_product(**self.payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\data_manager.py", line 69, in add_product
    product, exists = self.object_converter.convert_product_to_database(session=self.session, payload=payload)
  File "c:\Users\Joke\Desktop\Webscraper\webscraper\data_manager_package\object_converter.py", line 36, in convert_product_to_database
    exists = True if len(session.query(Product).filter_by(name=payload["name"]).all()) > 0 else False
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2768, in all
    return self._iter().all()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\query.py", line 2903, in _iter
    result = self.session.execute(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1691, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 1532, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "C:\Users\Joke\Desktop\Webscraper\webscraper_env\lib\site-packages\sqlalchemy\orm\session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: store_products.store_id, store_products.product_ean
[SQL: INSERT INTO store_products (store_id, product_ean, price, unit_price, shelf_name, shelf_href) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (2, 6419800020837, 3.45, '\n                    5.81€/l\n                ', 'Hyllyväli 60', 'https://storemap.jupa.s-cloud.fi/indoor/v1/?apiKey=U2FsdGVkX19gB2t7Y60b9qjh4pr6bmBf7a8aNb16tRU%3D&s=542862479&f=1&hs=ER9,ER8,ER6,ER5,ER2,ER12,ER10,ER11,ER3,ER4,ER7,ER13,ER1,ER14&l=dep,sec2,zon')]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
INFO: Closing spider (finished)
INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 8904,
 'downloader/request_count': 21,
 'downloader/request_method_count/GET': 21,
 'downloader/response_bytes': 937875,
 'downloader/response_count': 21,
 'downloader/response_status_count/200': 18,
 'downloader/response_status_count/302': 3,
 'elapsed_time_seconds': 7.765533,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 4, 22, 15, 12, 36, 194847),
 'httpcompression/response_bytes': 4228145,
 'httpcompression/response_count': 18,
 'log_count/DEBUG': 30,
 'log_count/ERROR': 12,
 'log_count/INFO': 10,
 'request_depth_max': 2,
 'response_received_count': 18,
 'scheduler/dequeued': 21,
 'scheduler/dequeued/memory': 21,
 'scheduler/enqueued': 21,
 'scheduler/enqueued/memory': 21,
 'spider_exceptions/IntegrityError': 1,
 'spider_exceptions/PendingRollbackError': 11,
 'start_time': datetime.datetime(2022, 4, 22, 15, 12, 28, 429314)}
INFO: Spider closed (finished)
